# Site settings
title: Saavesh's Website
author: Sherry Saavedra
email: sherrysaavedra@gmail.com
description: >
  My personal website built with Beautiful Jekyll to house my projects, blogs, and background.

baseurl: "" 
url: "https://saavesh.github.io/"

remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Social/contact links
social-network-links:
  github: Saavesh
  linkedin: sherrysaavedra115
  email: sherrysaavedra@gmail.com

# navigation
navbar-links:
  About Me: "about"
  Projects: "projects"
  Weekly Updates: "blog"
  Contact: "contact"

# Options
excerpt_length: 50
timezone: America/Los_Angeles

# Markdown
markdown: kramdown
kramdown:
  input: GFM
