# Site settings
title: Saavesh's Website
author: Sherry Saavedra
email: sherrysaavedra@gmail.com
description: >
  My personal website built with Beautiful Jekyll to house my projects, blogs, and background.

baseurl: "" 
url: "https://saavesh.github.io/"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# # Social/contact links
# social-network-links:
#   github: Saavesh
#   linkedin: sherrysaavedra115
#   email: sherrysaavedra@gmail.com


#   # Display the navigation sidebar at all times
# sidebar:
#   - title: About Me
#     url: /about/
#   - title: Projects
#     url: /projects/
#   - title: Weekly Updates
#     url: /blog/
#   - title: Contact
#     url: /contact/

excerpt_length: 50
timezone: America/Los_Angeles

# Markdown
markdown: kramdown
kramdown:
  input: GFM
