# Site settings
title: Sherry Saavedra - University of Colorado Boulder
author: Sherry Saavedra
email: sherrysaavedra@gmail.com
description: >
  Personal site to document my project updates, blog, and project development.

url: "https://saavesh.github.io"
baseurl: ""

remote_theme: daattali/beautiful-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

social-network-links:
  github: Saavesh
  linkedin: sherrysaavedra115
  email: sherrysaavedra@gmail.com

navbar-links:
  Home: "index"
  About Me: "about"
  Weekly Updates: "blog"

excerpt_length: 50
timezone: America/Los_Angeles

# Markdown
markdown: kramdown
kramdown:
  input: GFM
